# Generated by Django 5.2 on 2025-04-12 17:38

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='price',
            field=models.DecimalField(decimal_places=2, default=builtins.print, max_digits=10),
            preserve_default=False,
        ),
    ]
