# Generated by Django 5.2 on 2025-04-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('skilled_use', models.CharField(max_length=255, verbose_name='Skilled use')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
