# Generated by Django 5.2 on 2025-04-03 08:28

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_work', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplework',
            name='skilled_use',
        ),
        migrations.AddField(
            model_name='samplework',
            name='skill',
            field=models.CharField(default=builtins.print, max_length=255, verbose_name='Skilled use for sample project'),
            preserve_default=False,
        ),
    ]
