# Generated by Django 5.2 on 2025-04-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_work', '0003_remove_samplework_skilled_use_samplework_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplework',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Images'),
        ),
    ]
