# Generated by Django 5.2 on 2025-04-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_work', '0005_samplework_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplework',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='samplework',
            name='skill',
            field=models.CharField(max_length=255, verbose_name='Skill used for sample project'),
        ),
    ]
