# Generated by Django 5.2 on 2025-04-12 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_resme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='resme',
            new_name='resume',
        ),
    ]
